# -------------------------------------
# Aliases
# -------------------------------------
alias pubip='curl ipinfo.io'
alias ipa="ifconfig | grep inet"
alias ref='display_reference_file'
alias aliasup="cp $HOME/Code/Client/provision/linux/bash_aliases ~/.bash_aliases && source $HOME/.bashrc"
alias dirsize='du -h .'
alias diskspace="du -Sh | sort -n -r"
alias folders='du -h --max-depth=1'
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias sshkey='xclip -sel clip < $HOME/.ssh/depgithub.pub && xclip -o -sel clip'
alias sshlockdown='sudo cp $HOME/Code/Client/provision/linux/templates/sshd_config_soft /etc/ssh/sshd_config && sudo systemctl restart ssh'
alias gpt="ollama run llama3"
alias transcribe="whisper --model small"
alias mounte="sudo mount -t drvfs E: /mnt/e"
alias bkpaul="$HOME/Code/Client/backup/linux/bkprofile.sh paul"
alias bkfull="$HOME/Code/Client/backup/linux/bkprofile.sh paul-full"
alias bklinux="$HOME/Code/Client/backup/linux/bkprofile.sh paul-linux"

# Backup to a usb
function bkusb() {
    if [ -z "$1" ]; then
        echo " "
        echo "Usage: bkusb <profile> <destination>"
        echo "  Example: bkusb paul-linux /mnt/e/2411"
        echo " "
    else
        if [ -d "$2" ]; then
            bash "$HOME/Code/Client/backup/linux/bkprofile.sh" "$1" "$2"
        else
            echo "$2 does not exist"
        fi
    fi
}

# Syncup command - uploads the current folder to a destination folder such that the destination mirrors the current folder
function syncup() {
    if [ -z "$1" ]; then
        echo " "
        echo "Usage: syncup [destination]"
        echo " "
        echo "Uploads the content from the current folder and mirrors it into a destination folder"
        echo " "
        echo "Example: syncup paul@nas-homelab:$HOME/nas"
        echo " "
    else
        rsync -avzP --delete ./ "$1"
    fi
}

# Syncdown command - uploads the current folder to a destination folder such that the destination mirrors the current folder
function syncdown() {
    if [ -z "$1" ]; then
        echo " "
        echo "Usage: syncdown [source]"
        echo " "
        echo "Downloads the content from a source folder and mirrors it into the current folder"
        echo " "
        echo "Example: syncdown paul@nas-homelab:$HOME/nas"
        echo " "
    else
        rsync -avzP --delete "$1" ./
    fi
}

# Displays reference material, like cliff notes for man pages
function provision() {
    local filename="$HOME/Code/Client/provision/linux/install/$1.sh"

    if [ -z "$1" ]; then
        echo " "
        echo "Usage: provision [module]"
        echo " "
        echo "You can pick from the following modules"
        echo "--------------------------------------"
        find $HOME/Code/Client/provision/linux/install -maxdepth 1 -type f -exec basename {} \; | sed 's/\.[^.]*$//'
        echo " "
    else
        pushd .
        cd $HOME/Code/Client/provision/linux
        bash "install/$1.sh"
        popd
    fi
}

# Displays reference material, like cliff notes for man pages
function display_reference_file() {
    local filename="$HOME/Code/Client/provision/linux/reference/$1.sh"

    if [ -z "$1" ]; then
        echo " "
        echo "Usage: ref [topic]"
        echo " "
        echo "You can pick from the following topics"
        echo "--------------------------------------"
        find $HOME/Code/Client/provision/linux/reference -maxdepth 1 -type f -exec basename {} \; | sed 's/\.[^.]*$//'
        echo " "
    else
        highlight -O ansi $filename
    fi
}

# Extracts any archive(s) (if unp isn't installed)
extract() {
        for archive in "$@"; do
                if [ -f "$archive" ]; then
                        case $archive in
                        *.tar.bz2) tar xvjf $archive ;;
                        *.tar.gz) tar xvzf $archive ;;
                        *.bz2) bunzip2 $archive ;;
                        *.rar) rar x $archive ;;
                        *.gz) gunzip $archive ;;
                        *.tar) tar xvf $archive ;;
                        *.tbz2) tar xvjf $archive ;;
                        *.tgz) tar xvzf $archive ;;
                        *.zip) unzip $archive ;;
                        *.Z) uncompress $archive ;;
                        *.7z) 7z x $archive ;;
                        *) echo "don't know how to extract '$archive'..." ;;
                        esac
                else
                        echo "'$archive' is not a valid file!"
                fi
        done
}

# Searches for text in all files in the current folder
ftext() {
        # -i case-insensitive
        # -I ignore binary files
        # -H causes filename to be printed
        # -r recursive search
        # -n causes line number to be printed
        # optional: -F treat search term as a literal, not a regular expression
        # optional: -l only print filenames and not the matching lines ex. grep -irl "$1" *
        grep -iIHrn --color=always "$1" . | less -r
}

# Copy file with a progress bar
cpp() {
        set -e
        strace -q -ewrite cp -- "${1}" "${2}" 2>&1 |
                awk '{
        count += $NF
        if (count % 10 == 0) {
                percent = count / total_size * 100
                printf "%3d%% [", percent
                for (i=0;i<=percent;i++)
                        printf "="
                        printf ">"
                        for (i=percent;i<100;i++)
                                printf " "
                                printf "]\r"
                        }
                }
        END { print "" }' total_size="$(stat -c '%s' "${1}")" count=0
}

